/*
==============================================================================================
Magnitude Analysis
==============================================================================================
Purpose:
  - To quantify data and group results by specific dimensions.
  - For understanding data distribution across categories.

SQL functions used:
	- Aggregate Functions: SUM (), COUNT (), AVG()
	- GROUP BY, ORDER BY
==============================================================================================
*/

-- Find total customer by countries
SELECT
	cntry AS country,
	COUNT (customer_key) total_customers
FROM goldd.dim_customers
GROUP BY cntry;

-- Find total customer by gender
SELECT
	customer_gender,
	COUNT (customer_key) total_customers
FROM goldd.dim_customers
GROUP BY customer_gender;

-- Find the total products by category
SELECT
	category,
	COUNT (product_key) total_products
FROM goldd.dim_products
GROUP BY category;

-- what is the average costs in each category ?
SELECT
	category,
	SUM(product_cost)/ COUNT (product_key) average_cost
FROM goldd.dim_products
GROUP BY category;

-- What is the total revenue generated for each category?
SELECT
	p.category,
	SUM (sales_amount) total_revenue
FROM goldd.fact_sales s
LEFT JOIN goldd.dim_products p
ON s.product_key = p.product_key
GROUP BY p.category;

-- What is the total revenue generated by each customer ?
SELECT
s.customer_key,
customer_firstname,
customer_lastname,
SUM (sales_amount) AS total_revenue
FROM goldd.fact_sales s
LEFT JOIN goldd.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY s.customer_key,customer_firstname,customer_lastname;

-- What is the distribution of sold items across countries ?
SELECT
	c.cntry AS country,
	SUM (quantity) total_items
FROM goldd.fact_sales s
LEFT JOIN goldd.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.cntry;
